[tool.poetry]
name = "grunge-football"
version = "0.1.0"
description = ""
authors = ["Yuri Perin <y.perin@scalablesolutions.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
